# yaml formatter
formatter:
  draft:
    layout: post
    title:
    categories: []
    tags: []

  post:
    layout: post
    title:
    categories: []
    tags: []
    date:  # use current time automatically if there is no value
